#!/usr/bin/env python3
"""Write secure_link_keys.h with two fresh random 128-bit keys.

The output file holds secrets: it is listed in .gitignore and must never be
committed. Copy the same file to both ends of the link (STM32 and Feather).
"""
import secrets
import sys

def c_array(b):
    return ", ".join(f"0x{x:02X}" for x in b)

out = sys.argv[1] if len(sys.argv) > 1 else "secure_link_keys.h"
enc = secrets.token_bytes(16)   # secrets uses the OS's cryptographic random source
mic = secrets.token_bytes(16)

with open(out, "w") as f:
    f.write("/* GENERATED by gen_keys.py - SECRET, DO NOT COMMIT */\n")
    f.write("#ifndef SECURE_LINK_KEYS_H\n#define SECURE_LINK_KEYS_H\n\n")
    f.write("#include <stdint.h>\n\n")
    f.write("#define SL_DEV_ID 0x01U\n\n")
    f.write(f"static const uint8_t SL_ENC_KEY[16] = {{ {c_array(enc)} }};\n")
    f.write(f"static const uint8_t SL_MIC_KEY[16] = {{ {c_array(mic)} }};\n\n")
    f.write("#endif\n")
print(f"wrote {out}")
