#!/usr/bin/env python3
"""gen_signing_key.py - create the firmware signing key pair.

  keys/signing_key.pem   PRIVATE key. Never commit, never share. Back it up:
                         without it you cannot sign updates for boards whose
                         bootloader trusts the matching public key.
  bootloader/pubkey.h    PUBLIC key as a C array, compiled into the bootloader.
                         Safe to commit.

If the private key already exists it is NOT replaced (unless --force); only
pubkey.h is regenerated from it.
"""
import argparse
import hashlib
import os
import sys

try:
    from cryptography.hazmat.primitives import serialization
    from cryptography.hazmat.primitives.asymmetric import ec
except ImportError:
    sys.exit("error: needs the 'cryptography' package:  pip install cryptography")


def c_array(b):
    rows = [", ".join(f"0x{x:02X}" for x in b[i:i + 8]) for i in range(0, len(b), 8)]
    return ",\n  ".join(rows)


def pubkey_bytes(key):
    n = key.public_key().public_numbers()
    return n.x.to_bytes(32, "big") + n.y.to_bytes(32, "big")


def write_header(path, pub, key_path):
    key_id = hashlib.sha256(pub).hexdigest()[:8]
    with open(path, "w") as f:
        f.write(f"""/* GENERATED by tools/gen_signing_key.py from {key_path}.
 * PUBLIC key only: safe to commit. A bootloader built with this file starts
 * only images signed by the matching private key. */
#ifndef PUBKEY_H
#define PUBKEY_H

#include <stdint.h>

#define SIGNING_KEY_ID "{key_id}"   /* first 4 bytes of SHA-256(public key) */

/* ECDSA P-256 public key: X || Y, 32 bytes each, big-endian */
static const uint8_t SIGNING_PUBKEY[64] = {{
  {c_array(pub)}
}};

#endif
""")
    return key_id


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--key", default="keys/signing_key.pem")
    ap.add_argument("--header", default="bootloader/pubkey.h")
    ap.add_argument("--force", action="store_true", help="replace an existing private key (DANGEROUS)")
    args = ap.parse_args()

    if os.path.exists(args.key) and not args.force:
        with open(args.key, "rb") as f:
            key = serialization.load_pem_private_key(f.read(), password=None)
        print(f"using existing private key {args.key}")
    else:
        key = ec.generate_private_key(ec.SECP256R1())
        os.makedirs(os.path.dirname(args.key) or ".", exist_ok=True)
        pem = key.private_bytes(serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8,
                                serialization.NoEncryption())
        fd = os.open(args.key, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        with os.fdopen(fd, "wb") as f:
            f.write(pem)
        print(f"created NEW private key {args.key}  (keep it secret, back it up)")

    key_id = write_header(args.header, pubkey_bytes(key), args.key)
    print(f"wrote public key {args.header}  (key id {key_id})")


if __name__ == "__main__":
    main()
