/* feather_receiver.ino - Feather M0 + RFM95: receive and verify secure_link packets.
 *
 * Needs, in this sketch folder (copied from ../secure_link):
 *   aes128.c aes128.h aes_cmac.c aes_cmac.h secure_link.c secure_link.h
 *   secure_link_keys.h   (generated by gen_keys.py, the SAME file the STM32 uses)
 */
#include <SPI.h>
#include <LoRa.h>
#include "secure_link.h"
#include "secure_link_keys.h"

const int PIN_LORA_CS  = 8;
const int PIN_LORA_RST = 4;
const int PIN_LORA_IRQ = 3;

sl_keys  keys;
uint32_t last_fcnt = 0;          /* highest frame counter accepted so far */

static void print_hex(const uint8_t *b, int n)
{
  for (int i = 0; i < n; i++) {
    if (b[i] < 0x10) Serial.print('0');
    Serial.print(b[i], HEX);
    Serial.print(i + 1 < n ? " " : "");
  }
}

void setup() {
  Serial.begin(115200);
  while (!Serial && millis() < 5000) {}

  sl_init_keys(&keys, SL_ENC_KEY, SL_MIC_KEY);

  LoRa.setPins(PIN_LORA_CS, PIN_LORA_RST, PIN_LORA_IRQ);
  if (!LoRa.begin(868.1E6)) {
    Serial.println("LoRa init failed");
    while (1) {}
  }
  LoRa.setSyncWord(0x12);
  LoRa.enableCrc();
  Serial.println("Secure receiver listening on 868.1 MHz...");
}

void loop() {
  int size = LoRa.parsePacket();
  if (!size) return;

  uint8_t buf[SL_MAX_PACKET];
  int n = 0;
  while (LoRa.available()) {
    int b = LoRa.read();
    if (n < (int)sizeof(buf)) buf[n++] = (uint8_t)b;
  }
  if (size > (int)sizeof(buf)) {                 /* longer than any valid packet: noise */
    Serial.print("DROP length ");
    Serial.println(size);
    return;
  }

  /* What an eavesdropper sees */
  Serial.print("AIR [");
  Serial.print(n);
  Serial.print(" B]: ");
  print_hex(buf, n);
  Serial.println();

  uint8_t dev;
  uint8_t plain[SL_MAX_PAYLOAD + 1];
  int r = sl_open(&keys, &last_fcnt, buf, (uint8_t)n, &dev, plain, SL_MAX_PAYLOAD);

  if (r >= 0) {
    plain[r] = '\0';
    Serial.print("  OK   dev=");
    Serial.print(dev);
    Serial.print(" fcnt=");
    Serial.print((unsigned long)last_fcnt);
    Serial.print(" data=");
    Serial.print((char *)plain);
  } else {
    Serial.print("  REJECTED: ");
    if (r == SL_ERR_MIC)         Serial.print("bad MIC (altered, wrong key, or noise)");
    else if (r == SL_ERR_REPLAY) Serial.print("replay (fcnt not newer than ");
    else                         Serial.print("bad length");
    if (r == SL_ERR_REPLAY) { Serial.print((unsigned long)last_fcnt); Serial.print(")"); }
  }
  Serial.print("  RSSI ");
  Serial.print(LoRa.packetRssi());
  Serial.print(" dBm  SNR ");
  Serial.println(LoRa.packetSnr());
}
