/* feather_receiver.ino - Feather M0 + RFM95: receive and verify secure_link packets.
 *
 * Needs, in this sketch folder (copied from ../secure_link by sync_to_feather.sh):
 *   aes128.c aes128.h aes_cmac.c aes_cmac.h secure_link.c secure_link.h
 *   secure_link_keys.h   (generated by gen_keys.py, the SAME file the STM32 uses)
 * Library: "FlashStorage_SAMD" (Arduino Library Manager).
 *
 * Replay protection across receiver reboots:
 *   The highest accepted frame counter is kept in RAM, but RAM is lost on reset.
 *   So a CEILING is stored in flash: before any packet is delivered, the stored
 *   ceiling must be at or above its counter ("persist before deliver"). After a
 *   reboot the receiver resumes with last = ceiling, so no packet it accepted
 *   before can be accepted again. The ceiling is raised in steps of CEIL_STEP to
 *   limit flash wear; the cost is that up to CEIL_STEP genuine packets may be
 *   rejected after a receiver reboot, until the sender's counter passes it.
 */
#include <SPI.h>
#include <LoRa.h>
#include <FlashStorage_SAMD.h>
#include "secure_link.h"
#include "secure_link_keys.h"

const int PIN_LORA_CS  = 8;
const int PIN_LORA_RST = 4;
const int PIN_LORA_IRQ = 3;

/* ---------- Persistent replay ceiling ---------- */
const uint32_t CEIL_MAGIC = 0x534C4331UL;   /* "SLC1": marks a record we wrote */
const uint32_t CEIL_STEP  = 100;            /* flash writes per CEIL_STEP packets */

typedef struct {
  uint32_t magic;
  uint32_t ceil;
  uint32_t inv;                             /* ~ceil: detects a torn or corrupted record */
} CeilRec;

/* Two copies in two separate flash rows. Each write erases a whole row, so a
 * power cut mid-write can destroy one copy; the other one survives. */
FlashStorage(ceilA, CeilRec);
FlashStorage(ceilB, CeilRec);

uint32_t stored_ceil = 0;

static bool rec_valid(const CeilRec &r) { return r.magic == CEIL_MAGIC && r.inv == ~r.ceil; }

static bool load_ceiling(uint32_t *out)
{
  CeilRec a, b;
  ceilA.read(a);              /* FlashStorage_SAMD fills in the variable you pass */
  ceilB.read(b);
  bool va = rec_valid(a), vb = rec_valid(b);
  if (!va && !vb) return false;
  if (va && vb)   *out = (a.ceil > b.ceil) ? a.ceil : b.ceil;
  else            *out = va ? a.ceil : b.ceil;
  return true;
}

/* Write copy A, then copy B. If power fails during A, B still holds the old
 * ceiling, and nothing above it has been delivered yet. */
static void save_ceiling(uint32_t c)
{
  CeilRec r = { CEIL_MAGIC, c, ~c };
  ceilA.write(r);
  ceilB.write(r);
  stored_ceil = c;
}

/* ---------- Link state ---------- */
sl_keys  keys;
uint32_t last_fcnt = 0;          /* highest frame counter accepted (or the restored ceiling) */

static void print_hex(const uint8_t *b, int n)
{
  for (int i = 0; i < n; i++) {
    if (b[i] < 0x10) Serial.print('0');
    Serial.print(b[i], HEX);
    Serial.print(i + 1 < n ? " " : "");
  }
}

void setup() {
  Serial.begin(115200);
  while (!Serial && millis() < 5000) {}

  sl_init_keys(&keys, SL_ENC_KEY, SL_MIC_KEY);

  uint32_t c;
  if (load_ceiling(&c)) {
    stored_ceil = c;
    last_fcnt = c;
    Serial.print("Replay floor restored from flash: accepting only fcnt > ");
    Serial.println((unsigned long)c);
  } else {
    Serial.println("No stored replay floor (fresh flash): accepting from fcnt 1");
  }

  LoRa.setPins(PIN_LORA_CS, PIN_LORA_RST, PIN_LORA_IRQ);
  if (!LoRa.begin(868.1E6)) {
    Serial.println("LoRa init failed");
    while (1) {}
  }
  LoRa.setSyncWord(0x12);
  LoRa.enableCrc();
  Serial.println("Secure receiver listening on 868.1 MHz...");
}

void loop() {
  int size = LoRa.parsePacket();
  if (!size) return;

  uint8_t buf[SL_MAX_PACKET];
  int n = 0;
  while (LoRa.available()) {
    int b = LoRa.read();
    if (n < (int)sizeof(buf)) buf[n++] = (uint8_t)b;
  }
  if (size > (int)sizeof(buf)) {                 /* longer than any valid packet: noise */
    Serial.print("DROP length ");
    Serial.println(size);
    return;
  }

  Serial.print("AIR [");
  Serial.print(n);
  Serial.print(" B]: ");
  print_hex(buf, n);
  Serial.println();

  uint8_t dev;
  uint8_t plain[SL_MAX_PAYLOAD + 1];
  int r = sl_open(&keys, &last_fcnt, buf, (uint8_t)n, &dev, plain, SL_MAX_PAYLOAD);

  if (r >= 0) {
    /* Persist before deliver: raise the stored ceiling first if needed */
    if (last_fcnt > stored_ceil) {
      save_ceiling(last_fcnt + CEIL_STEP);
      Serial.print("  (replay floor saved to flash: ");
      Serial.print((unsigned long)stored_ceil);
      Serial.println(")");
    }
    plain[r] = '\0';
    Serial.print("  OK   dev=");
    Serial.print(dev);
    Serial.print(" fcnt=");
    Serial.print((unsigned long)last_fcnt);
    Serial.print(" data=");
    Serial.print((char *)plain);
  } else {
    Serial.print("  REJECTED: ");
    if (r == SL_ERR_MIC)         Serial.print("bad MIC (altered, wrong key, or noise)");
    else if (r == SL_ERR_REPLAY) Serial.print("replay (fcnt not newer than ");
    else                         Serial.print("bad length");
    if (r == SL_ERR_REPLAY) { Serial.print((unsigned long)last_fcnt); Serial.print(")"); }
  }
  Serial.print("  RSSI ");
  Serial.print(LoRa.packetRssi());
  Serial.print(" dBm  SNR ");
  Serial.println(LoRa.packetSnr());
}
